version: '3.8'

services:
  apache:
    image: httpd:latest
    volumes:
      - ./codi/starship-sorades-13k:/usr/local/apache2/htdocs
    expose:
      - "80"
    deploy:
      replicas: 10   # Escala a 10 instancias
      restart_policy:
        condition: on-failure
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: cNginx
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
